/**
 * Unit tests for sprint-index-manager
 *
 * Tests all core functions using temporary directories for filesystem isolation
 */

import {
  loadSprintIndex,
  saveSprintIndex,
  addSprintToIndex,
  updateSprintInIndex,
  regenerateSprintIndex,
} from '../sprint-index-manager.js';
import { fileExists, readFile } from '../file-utils.js';
import { mkdtemp, rm, mkdir, writeFile as fsWriteFile } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';
import { stringify as stringifyYaml, parse as parseYaml } from 'yaml';
import type { SprintIndex, SprintIndexEntry } from '../../types/sprint-index.js';

describe('sprint-index-manager', () => {
  let testDir: string;
  let originalCwd: string;
  let planningDir: string;
  let indexPath: string;

  beforeEach(async () => {
    // Save original working directory
    originalCwd = process.cwd();

    // Create temporary test directory
    testDir = await mkdtemp(join(tmpdir(), 'sprint-index-test-'));

    // Change to test directory
    process.chdir(testDir);

    // Create planning directory
    planningDir = join(testDir, 'planning');
    await mkdir(planningDir, { recursive: true });

    indexPath = join(planningDir, 'sprint-index.yaml');
  });

  afterEach(async () => {
    // Always restore original working directory first
    process.chdir(originalCwd);

    // Clean up test directory
    try {
      await rm(testDir, { recursive: true, force: true });
    } catch (error) {
      console.error(`Failed to cleanup test directory ${testDir}:`, error);
    }
  });

  describe('loadSprintIndex', () => {
    it('should return empty index when file does not exist', async () => {
      const index = await loadSprintIndex();

      expect(index).toBeDefined();
      expect(index.version).toBe('1.0');
      expect(index.totalSprints).toBe(0);
      expect(index.activeSprints).toBe(0);
      expect(index.completedSprints).toBe(0);
      expect(index.sprints).toEqual([]);
      expect(index.statistics.byStatus.complete).toBe(0);
    });

    it('should load valid index from disk', async () => {
      // Create a valid index file
      const validIndex: SprintIndex = {
        version: '1.0',
        generatedAt: '2026-07-30T12:00:00Z',
        totalSprints: 1,
        activeSprints: 0,
        completedSprints: 1,
        sprints: [
          {
            id: 'sprint-1-abc123',
            title: 'Test Sprint',
            status: 'complete',
            owner: 'Test Owner',
            createdAt: '2026-07-30T10:00:00Z',
            completedAt: '2026-07-30T18:00:00Z',
            manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
            branch: 'feature/sprint-1-abc123-test',
          },
        ],
        statistics: {
          byStatus: {
            planning: 0,
            'in-progress': 0,
            validating: 0,
            verifying: 0,
            published: 0,
            complete: 1,
          },
          byCompletionMode: {
            normal: 0,
            forced: 0,
          },
        },
      };

      await fsWriteFile(indexPath, stringifyYaml(validIndex), 'utf-8');

      const loaded = await loadSprintIndex();

      expect(loaded.totalSprints).toBe(1);
      expect(loaded.sprints).toHaveLength(1);
      expect(loaded.sprints[0].id).toBe('sprint-1-abc123');
    });

    it('should throw error when index file contains invalid YAML', async () => {
      // Write invalid YAML
      await fsWriteFile(indexPath, 'invalid: yaml: content: [', 'utf-8');

      await expect(loadSprintIndex()).rejects.toThrow(
        /Failed to parse sprint index/
      );
    });
  });

  describe('saveSprintIndex', () => {
    it('should save index to disk with header comment', async () => {
      const index: SprintIndex = {
        version: '1.0',
        generatedAt: '2026-07-30T12:00:00Z',
        totalSprints: 0,
        activeSprints: 0,
        completedSprints: 0,
        sprints: [],
        statistics: {
          byStatus: {
            planning: 0,
            'in-progress': 0,
            validating: 0,
            verifying: 0,
            published: 0,
            complete: 0,
          },
          byCompletionMode: {
            normal: 0,
            forced: 0,
          },
        },
      };

      await saveSprintIndex(index);

      // Read file and check content
      const fs = await import('fs/promises');
      const content = await fs.readFile(indexPath, 'utf-8');

      expect(content).toContain('DO NOT EDIT THIS FILE MANUALLY');
      expect(content).toContain('version: "1.0"');
      expect(content).toContain('totalSprints: 0');
    });

    it('should create backup when overwriting existing index', async () => {
      // Create initial index
      const index1: SprintIndex = {
        version: '1.0',
        generatedAt: '2026-07-30T12:00:00Z',
        totalSprints: 1,
        activeSprints: 0,
        completedSprints: 1,
        sprints: [
          {
            id: 'sprint-1-abc123',
            title: 'Test Sprint',
            status: 'complete',
            owner: 'Test Owner',
            createdAt: '2026-07-30T10:00:00Z',
            manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
            branch: 'feature/sprint-1-abc123-test',
          },
        ],
        statistics: {
          byStatus: {
            planning: 0,
            'in-progress': 0,
            validating: 0,
            verifying: 0,
            published: 0,
            complete: 1,
          },
          byCompletionMode: {
            normal: 0,
            forced: 0,
          },
        },
      };

      await saveSprintIndex(index1);

      // Overwrite with new index
      const index2 = { ...index1, totalSprints: 2 };
      await saveSprintIndex(index2);

      // Check backup exists
      const fs = await import('fs/promises');
      const backupPath = `${indexPath}.backup`;
      const backupExists = await fs
        .access(backupPath)
        .then(() => true)
        .catch(() => false);

      expect(backupExists).toBe(true);

      // Verify backup contains original data
      if (backupExists) {
        const backupContent = await fs.readFile(backupPath, 'utf-8');
        expect(backupContent).toContain('totalSprints: 1');
      }
    });

    it('should update generatedAt timestamp when saving', async () => {
      const index: SprintIndex = {
        version: '1.0',
        generatedAt: '2026-07-30T12:00:00Z', // Old timestamp
        totalSprints: 0,
        activeSprints: 0,
        completedSprints: 0,
        sprints: [],
        statistics: {
          byStatus: {
            planning: 0,
            'in-progress': 0,
            validating: 0,
            verifying: 0,
            published: 0,
            complete: 0,
          },
          byCompletionMode: {
            normal: 0,
            forced: 0,
          },
        },
      };

      await saveSprintIndex(index);

      const loaded = await loadSprintIndex();

      // Timestamp should be updated
      expect(loaded.generatedAt).not.toBe('2026-07-30T12:00:00Z');
      expect(new Date(loaded.generatedAt).getTime()).toBeGreaterThan(
        new Date('2026-07-30T12:00:00Z').getTime()
      );
    });
  });

  describe('addSprintToIndex', () => {
    it('should add new sprint entry to empty index', async () => {
      const entry: SprintIndexEntry = {
        id: 'sprint-1-abc123',
        title: 'New Sprint',
        status: 'in-progress',
        owner: 'Test Owner',
        createdAt: '2026-07-30T10:00:00Z',
        manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
        branch: 'feature/sprint-1-abc123-new',
      };

      await addSprintToIndex(entry);

      const index = await loadSprintIndex();

      expect(index.totalSprints).toBe(1);
      expect(index.activeSprints).toBe(1);
      expect(index.completedSprints).toBe(0);
      expect(index.sprints).toHaveLength(1);
      expect(index.sprints[0].id).toBe('sprint-1-abc123');
      expect(index.statistics.byStatus['in-progress']).toBe(1);
    });

    it('should sort sprints by number after adding', async () => {
      // Add sprint 2 first
      await addSprintToIndex({
        id: 'sprint-2-def456',
        title: 'Second Sprint',
        status: 'complete',
        owner: 'Test Owner',
        createdAt: '2026-07-30T11:00:00Z',
        manifestPath: 'planning/sprint-2-def456/sprint-manifest.yaml',
        branch: 'feature/sprint-2-def456',
      });

      // Add sprint 1
      await addSprintToIndex({
        id: 'sprint-1-abc123',
        title: 'First Sprint',
        status: 'complete',
        owner: 'Test Owner',
        createdAt: '2026-07-30T10:00:00Z',
        manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
        branch: 'feature/sprint-1-abc123',
      });

      const index = await loadSprintIndex();

      // Should be sorted by sprint number
      expect(index.sprints[0].id).toBe('sprint-1-abc123');
      expect(index.sprints[1].id).toBe('sprint-2-def456');
    });

    it('should update statistics when adding sprint', async () => {
      await addSprintToIndex({
        id: 'sprint-1-abc123',
        title: 'Sprint 1',
        status: 'complete',
        owner: 'Owner 1',
        createdAt: '2026-07-30T10:00:00Z',
        completedAt: '2026-07-30T18:00:00Z',
        completionMode: 'normal',
        manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
        branch: 'feature/sprint-1-abc123',
      });

      const index = await loadSprintIndex();

      expect(index.statistics.byStatus.complete).toBe(1);
      expect(index.statistics.byCompletionMode.normal).toBe(1);
    });

    it('should throw error when adding duplicate sprint', async () => {
      const entry: SprintIndexEntry = {
        id: 'sprint-1-abc123',
        title: 'Sprint 1',
        status: 'in-progress',
        owner: 'Test Owner',
        createdAt: '2026-07-30T10:00:00Z',
        manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
        branch: 'feature/sprint-1-abc123',
      };

      await addSprintToIndex(entry);

      // Try to add same sprint again
      await expect(addSprintToIndex(entry)).rejects.toThrow(
        /already exists in index/
      );
    });
  });

  describe('updateSprintInIndex', () => {
    it('should update existing sprint entry', async () => {
      // Add initial sprint
      await addSprintToIndex({
        id: 'sprint-1-abc123',
        title: 'Original Title',
        status: 'in-progress',
        owner: 'Test Owner',
        createdAt: '2026-07-30T10:00:00Z',
        manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
        branch: 'feature/sprint-1-abc123',
      });

      // Update sprint
      await updateSprintInIndex('sprint-1-abc123', {
        status: 'complete',
        completedAt: '2026-07-30T18:00:00Z',
        completionMode: 'normal',
      });

      const index = await loadSprintIndex();

      expect(index.sprints[0].status).toBe('complete');
      expect(index.sprints[0].completedAt).toBe('2026-07-30T18:00:00Z');
      expect(index.sprints[0].completionMode).toBe('normal');
      expect(index.activeSprints).toBe(0);
      expect(index.completedSprints).toBe(1);
    });

    it('should recompute statistics after update', async () => {
      await addSprintToIndex({
        id: 'sprint-1-abc123',
        title: 'Sprint 1',
        status: 'in-progress',
        owner: 'Test Owner',
        createdAt: '2026-07-30T10:00:00Z',
        manifestPath: 'planning/sprint-1-abc123/sprint-manifest.yaml',
        branch: 'feature/sprint-1-abc123',
      });

      await updateSprintInIndex('sprint-1-abc123', {
        status: 'complete',
      });

      const index = await loadSprintIndex();

      expect(index.statistics.byStatus['in-progress']).toBe(0);
      expect(index.statistics.byStatus.complete).toBe(1);
    });

    it('should throw error when updating non-existent sprint', async () => {
      await expect(
        updateSprintInIndex('sprint-999-nonexistent', { status: 'complete' })
      ).rejects.toThrow(/not found in index/);
    });
  });

  describe('regenerateSprintIndex', () => {
    it('should regenerate index from zero manifests', async () => {
      const { index, skippedDirectories, repairedDirectories } = await regenerateSprintIndex();

      expect(index.totalSprints).toBe(0);
      expect(index.sprints).toEqual([]);
      expect(skippedDirectories).toBe(0);
      expect(repairedDirectories).toBe(0);
    });

    it('should regenerate index from single manifest', async () => {
      // Create sprint directory and manifest
      const sprintDir = join(planningDir, 'sprint-1-abc123');
      await mkdir(sprintDir, { recursive: true });

      const manifest = {
        id: 'sprint-1-abc123',
        title: 'Test Sprint',
        goal: 'Test goal',
        owner: 'Test Owner',
        createdAt: '2026-07-30T10:00:00Z',
        status: 'complete',
        links: {
          branch: 'feature/sprint-1-abc123-test',
          pr: 'https://github.com/test/repo/pull/1',
        },
      };

      await fsWriteFile(
        join(sprintDir, 'sprint-manifest.yaml'),
        stringifyYaml(manifest),
        'utf-8'
      );

      const { index, skippedDirectories, repairedDirectories } = await regenerateSprintIndex();

      expect(index.totalSprints).toBe(1);
      expect(index.sprints[0].id).toBe('sprint-1-abc123');
      expect(index.sprints[0].pr).toBe('https://github.com/test/repo/pull/1');
      expect(skippedDirectories).toBe(0);
      expect(repairedDirectories).toBe(0);
    });

    it('should regenerate index from multiple manifests and sort by number', async () => {
      // Create sprint 3
      const sprint3Dir = join(planningDir, 'sprint-3-ghi789');
      await mkdir(sprint3Dir, { recursive: true });
      await fsWriteFile(
        join(sprint3Dir, 'sprint-manifest.yaml'),
        stringifyYaml({
          id: 'sprint-3-ghi789',
          title: 'Sprint 3',
          goal: 'Goal 3',
          owner: 'Owner',
          createdAt: '2026-07-30T12:00:00Z',
          status: 'complete',
          links: { branch: 'feature/sprint-3-ghi789' },
        }),
        'utf-8'
      );

      // Create sprint 1
      const sprint1Dir = join(planningDir, 'sprint-1-abc123');
      await mkdir(sprint1Dir, { recursive: true });
      await fsWriteFile(
        join(sprint1Dir, 'sprint-manifest.yaml'),
        stringifyYaml({
          id: 'sprint-1-abc123',
          title: 'Sprint 1',
          goal: 'Goal 1',
          owner: 'Owner',
          createdAt: '2026-07-30T10:00:00Z',
          status: 'complete',
          links: { branch: 'feature/sprint-1-abc123' },
        }),
        'utf-8'
      );

      // Create sprint 2
      const sprint2Dir = join(planningDir, 'sprint-2-def456');
      await mkdir(sprint2Dir, { recursive: true });
      await fsWriteFile(
        join(sprint2Dir, 'sprint-manifest.yaml'),
        stringifyYaml({
          id: 'sprint-2-def456',
          title: 'Sprint 2',
          goal: 'Goal 2',
          owner: 'Owner',
          createdAt: '2026-07-30T11:00:00Z',
          status: 'in-progress',
          links: { branch: 'feature/sprint-2-def456' },
        }),
        'utf-8'
      );

      const { index, skippedDirectories, repairedDirectories } = await regenerateSprintIndex();

      expect(index.totalSprints).toBe(3);
      expect(index.activeSprints).toBe(1);
      expect(index.completedSprints).toBe(2);
      expect(skippedDirectories).toBe(0);
      expect(repairedDirectories).toBe(0);

      // Should be sorted by sprint number
      expect(index.sprints[0].id).toBe('sprint-1-abc123');
      expect(index.sprints[1].id).toBe('sprint-2-def456');
      expect(index.sprints[2].id).toBe('sprint-3-ghi789');
    });

    it('should handle corrupted manifest gracefully', async () => {
      // Create valid sprint
      const sprint1Dir = join(planningDir, 'sprint-1-abc123');
      await mkdir(sprint1Dir, { recursive: true });
      await fsWriteFile(
        join(sprint1Dir, 'sprint-manifest.yaml'),
        stringifyYaml({
          id: 'sprint-1-abc123',
          title: 'Sprint 1',
          goal: 'Goal 1',
          owner: 'Owner',
          createdAt: '2026-07-30T10:00:00Z',
          status: 'complete',
          links: { branch: 'feature/sprint-1-abc123' },
        }),
        'utf-8'
      );

      // Create corrupted sprint
      const sprint2Dir = join(planningDir, 'sprint-2-def456');
      await mkdir(sprint2Dir, { recursive: true });
      await fsWriteFile(
        join(sprint2Dir, 'sprint-manifest.yaml'),
        'invalid: yaml: [',
        'utf-8'
      );

      const { index, skippedDirectories, repairedDirectories } = await regenerateSprintIndex();

      // Should only include the valid sprint
      expect(index.totalSprints).toBe(1);
      expect(index.sprints[0].id).toBe('sprint-1-abc123');
      expect(skippedDirectories).toBe(0);
      expect(repairedDirectories).toBe(0);
    });

    it('should repair sprint directories with missing manifests when repair=true', async () => {
      // Create valid sprint with manifest
      const sprint1Dir = join(planningDir, 'sprint-1-abc123');
      await mkdir(sprint1Dir, { recursive: true });
      await fsWriteFile(
        join(sprint1Dir, 'sprint-manifest.yaml'),
        stringifyYaml({
          id: 'sprint-1-abc123',
          title: 'Sprint 1',
          goal: 'Goal 1',
          owner: 'Owner 1',
          createdAt: '2026-07-30T10:00:00Z',
          status: 'complete',
          links: { branch: 'feature/sprint-1-abc123' },
        }),
        'utf-8'
      );

      // Create sprint directory without manifest but with files
      const sprint2Dir = join(planningDir, 'sprint-2-def456');
      await mkdir(sprint2Dir, { recursive: true });
      await fsWriteFile(join(sprint2Dir, 'request-log.md'), '# Request Log\n', 'utf-8');

      // Create empty sprint directory (should be skipped)
      const sprint3Dir = join(planningDir, 'sprint-3-empty');
      await mkdir(sprint3Dir, { recursive: true });

      // Regenerate with repair enabled
      const { index, skippedDirectories, repairedDirectories } = await regenerateSprintIndex({ repair: true });

      // Should include both valid and repaired sprints
      expect(index.totalSprints).toBe(2);
      expect(repairedDirectories).toBe(1);
      expect(skippedDirectories).toBe(1); // Empty directory

      // Check the repaired manifest was created
      const manifestExists = await fileExists(join(sprint2Dir, 'sprint-manifest.yaml'));
      expect(manifestExists).toBe(true);

      // Verify repaired manifest content
      const repairedContent = await readFile(join(sprint2Dir, 'sprint-manifest.yaml'));
      const repairedManifest = parseYaml(repairedContent);
      expect(repairedManifest.id).toBe('sprint-2-def456');
      expect(repairedManifest.title).toContain('Sprint 2');
      expect(repairedManifest.title).toContain('Auto-generated');
      expect(repairedManifest.status).toBe('complete');
      expect(repairedManifest.owner).toBe('Unknown');
    });

    it('should skip directories without manifests when repair=false', async () => {
      // Create sprint directory without manifest
      const sprintDir = join(planningDir, 'sprint-1-abc123');
      await mkdir(sprintDir, { recursive: true });
      await fsWriteFile(join(sprintDir, 'request-log.md'), '# Request Log\n', 'utf-8');

      // Regenerate without repair
      const { index, skippedDirectories, repairedDirectories } = await regenerateSprintIndex({ repair: false });

      expect(index.totalSprints).toBe(0);
      expect(skippedDirectories).toBe(1);
      expect(repairedDirectories).toBe(0);

      // Manifest should not have been created
      const manifestExists = await fileExists(join(sprintDir, 'sprint-manifest.yaml'));
      expect(manifestExists).toBe(false);
    });

    it('should scan legacy sprints in planning root when archive mode is enabled', async () => {
      // Create archive config
      const archiveConfig = {
        archive: {
          enabled: true,
          autoArchive: {
            enabled: true,
            criteria: 'hybrid',
            ageDays: 30,
            keepCount: 10,
            schedule: 'manual',
          },
          knowledge: {
            extractOnComplete: false,
            categories: ['lessons'],
            aggregateOnExtraction: false,
          },
          migration: {
            completed: true,
            backupPath: 'sprint-index.yaml.backup',
          },
        },
      };
      await fsWriteFile(
        join(planningDir, 'archive-config.yaml'),
        stringifyYaml(archiveConfig),
        'utf-8'
      );

      // Create active/ and archive/ directories
      await mkdir(join(planningDir, 'active'), { recursive: true });
      await mkdir(join(planningDir, 'archive', '2026'), { recursive: true });

      // Create sprint in active/
      const activeSprint = join(planningDir, 'active', 'sprint-1-active');
      await mkdir(activeSprint, { recursive: true });
      const activeManifest = {
        id: 'sprint-1-active',
        title: 'Active Sprint',
        goal: 'Test',
        owner: 'test',
        status: 'in-progress',
        createdAt: new Date().toISOString(),
        branch: 'feature/sprint-1-active',
      };
      await fsWriteFile(
        join(activeSprint, 'sprint-manifest.yaml'),
        stringifyYaml(activeManifest),
        'utf-8'
      );

      // Create sprint in archive/
      const archivedSprint = join(planningDir, 'archive', '2026', 'sprint-2-archived');
      await mkdir(archivedSprint, { recursive: true });
      const archivedManifest = {
        id: 'sprint-2-archived',
        title: 'Archived Sprint',
        goal: 'Test',
        owner: 'test',
        status: 'complete',
        createdAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        branch: 'feature/sprint-2-archived',
      };
      await fsWriteFile(
        join(archivedSprint, 'sprint-manifest.yaml'),
        stringifyYaml(archivedManifest),
        'utf-8'
      );

      // Create legacy sprint in planning root (not migrated)
      const legacySprint = join(planningDir, 'sprint-3-legacy');
      await mkdir(legacySprint, { recursive: true });
      const legacyManifest = {
        id: 'sprint-3-legacy',
        title: 'Legacy Sprint',
        goal: 'Test',
        owner: 'test',
        status: 'complete',
        createdAt: new Date().toISOString(),
        completedAt: new Date().toISOString(),
        branch: 'feature/sprint-3-legacy',
      };
      await fsWriteFile(
        join(legacySprint, 'sprint-manifest.yaml'),
        stringifyYaml(legacyManifest),
        'utf-8'
      );

      // Regenerate index
      const { index } = await regenerateSprintIndex();

      // Should find all 3 sprints: active, archived, and legacy
      expect(index.totalSprints).toBe(3);
      expect(index.activeSprints).toBe(1);
      expect(index.completedSprints).toBe(2);

      // Verify all sprints are in the index
      const sprintIds = index.sprints.map((s) => s.id);
      expect(sprintIds).toContain('sprint-1-active');
      expect(sprintIds).toContain('sprint-2-archived');
      expect(sprintIds).toContain('sprint-3-legacy');

      // Verify manifest paths
      const activeSp = index.sprints.find((s) => s.id === 'sprint-1-active');
      const archivedSp = index.sprints.find((s) => s.id === 'sprint-2-archived');
      const legacySp = index.sprints.find((s) => s.id === 'sprint-3-legacy');

      expect(activeSp?.manifestPath).toContain('planning/active/sprint-1-active');
      expect(archivedSp?.manifestPath).toContain('planning/archive/2026/sprint-2-archived');
      expect(legacySp?.manifestPath).toContain('planning/sprint-3-legacy');
    });
  });
});
