#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
agents_file="${repo_root}/AGENTS.md"
retro_file="${repo_root}/planning/sprint-1-a9f3c2/retro.md"
learnings_file="${repo_root}/planning/sprint-1-a9f3c2/key-learnings.md"

echo "Installing dependencies..."
cd "${repo_root}"
npm ci

echo "Building project..."
npm run build

echo "Running tests..."
npm test -- --runInBand --passWithNoTests

echo "Checking Human-LLM partnership policy..."
grep -Fq '# AGENTS.md — Human–LLM Sprint Protocol v3.0' "${agents_file}"
grep -Fq '## 🧠 Partnership, Authority, and Capabilities' "${agents_file}"
grep -Fq '## 2.5.1 Intentional Commit Protocol' "${agents_file}"
grep -Fq '### Human-Only Release (separate from sprint publication)' "${agents_file}"
grep -Fq '## 2.9.1 Learning Artifacts for Future Extraction' "${agents_file}"

echo "Checking deprecated or contradictory policy language..."
if grep -Eq 'LLM-led sprint|When a shipping sprint cuts a version|Generated by LLM agent according to Sprint Protocol' "${agents_file}"; then
  echo "Found deprecated protocol language." >&2
  exit 1
fi

echo "Checking extraction-ready record schemas..."
grep -Fq '### OBS-001' "${agents_file}"
grep -Fq '### PART-001' "${agents_file}"
grep -Fq '### LEARN-001' "${agents_file}"
grep -Fq -- '- Confidence: low | medium | high' "${agents_file}"
grep -Fq -- '- Tags: [tag-one, tag-two]' "${agents_file}"

echo "Checking produced learning artifacts..."
grep -Eq '^### OBS-[0-9]{3} ' "${retro_file}"
grep -Eq '^### PART-[0-9]{3} ' "${retro_file}"
grep -Eq '^### FOLLOW-[0-9]{3} ' "${retro_file}"
grep -Eq '^### LEARN-[0-9]{3} ' "${learnings_file}"
grep -Eq '^- Confidence: (low|medium|high)$' "${learnings_file}"
grep -Eq '^- Tags: \[[a-z0-9-]+(, [a-z0-9-]+)*\]$' "${learnings_file}"

echo "Validation complete."
