#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
agents_file="${repo_root}/AGENTS.md"
retro_file="${repo_root}/planning/sprint-1-a9f3c2/retro.md"
learnings_file="${repo_root}/planning/sprint-1-a9f3c2/key-learnings.md"
backlog_file="${repo_root}/planning/sprint-1-a9f3c2/backlog.yaml"
reference_dir="${repo_root}/documentation/reference"
manifest_reference="${reference_dir}/sprint-manifest-example.yaml"
backlog_reference="${reference_dir}/backlog-example.yaml"
plan_reference="${reference_dir}/execution-plan-template.md"
validation_reference="${reference_dir}/validate-deliverable-example.sh"
publication_reference="${reference_dir}/publication-example.yaml"
verification_reference="${reference_dir}/verification-report-template.md"
retro_reference="${reference_dir}/retro-template.md"
learnings_reference="${reference_dir}/key-learnings-template.md"

echo "Installing dependencies..."
cd "${repo_root}"
npm ci

echo "Building project..."
npm run build

echo "Running tests..."
npm test -- --runInBand --passWithNoTests

echo "Checking Human-LLM partnership policy..."
grep -Fq '# AGENTS.md — Human–LLM Sprint Protocol v3.0' "${agents_file}"
grep -Fq '## 🧠 Partnership, Authority, and Capabilities' "${agents_file}"
grep -Fq '## 2.5.1 Intentional Commit Protocol' "${agents_file}"
grep -Fq '## 2.5.2 Human Follow-Up Loop' "${agents_file}"
grep -Fq '## 2.3.1 Backlog Accountability Contract' "${agents_file}"
grep -Fq '`backlog.yaml` is the accountability contract for sprint commitments and current work state' "${agents_file}"
grep -Fq 'Status changes are part of execution, not end-of-sprint bookkeeping.' "${agents_file}"
grep -Fq 'Change `in-progress` to `done` only after every acceptance criterion is verified.' "${agents_file}"
grep -Fq 'Stop → Clarify → Append → Continue' "${agents_file}"
grep -Fq 'Place it at the end of `items` unless the human specifies another position' "${agents_file}"
grep -Fq 'Record every sprint-relevant Human–LLM turn in `request-log.md`' "${agents_file}"
grep -Fq 'Routine read-only discovery, navigation, and repeated diagnostic checks may be summarized or omitted.' "${agents_file}"
if grep -Fq 'Log every meaningful shell and git operation into `request-log.md`' "${agents_file}"; then
  echo "Found superseded operation-centered logging requirement." >&2
  exit 1
fi
grep -Fq '# 🔀 2.8 Completion Handoff — *Push Required, PR Optional*' "${agents_file}"
grep -Fq 'The Sprint Protocol does not require a Pull Request' "${agents_file}"
grep -Fq '### Human-Defined Release (optional and separate from sprint completion)' "${agents_file}"
grep -Fq '# 🧪 2.6 Validation and Definition of Done' "${agents_file}"
grep -Fq '**Required:** must run and pass; never mask failure' "${agents_file}"
grep -Fq 'Documentation, research, and planning work instead validates applicable schemas' "${agents_file}"
grep -Fq '# 🧱 3. Project Structure' "${agents_file}"
grep -Fq '# 🧠 7. Sprint Lifecycle Summary' "${agents_file}"
grep -Fq '## 2.9.1 Learning Artifacts for Future Extraction' "${agents_file}"

echo "Checking phase-loaded artifact references..."
for reference in "${manifest_reference}" "${backlog_reference}" "${plan_reference}" "${validation_reference}" "${publication_reference}" "${verification_reference}" "${retro_reference}" "${learnings_reference}"; do
  test -f "${reference}"
  grep -Fq "documentation/reference/$(basename "${reference}")" "${agents_file}"
done
grep -Fq 'status: planning' "${manifest_reference}"
grep -Fq 'completionMode: null' "${manifest_reference}"

echo "Checking deprecated or contradictory policy language..."
if grep -Eq 'LLM-led sprint|When a shipping sprint cuts a version|Generated by LLM agent according to Sprint Protocol' "${agents_file}"; then
  echo "Found deprecated protocol language." >&2
  exit 1
fi
if grep -Eqi 'brat|BitBrat|Real GitHub PR Required|LLM Pushes \+ Opens PR|Push \+ PR' "${agents_file}"; then
  echo "Found project-specific release text or mandatory PR language." >&2
  exit 1
fi
if grep -Fq 'Deviations from the implementation plan' "${agents_file}"; then
  echo "Found superseded implementation-plan terminology." >&2
  exit 1
fi
if grep -Eq '^# .*Project-Wide Definition of Done|^# .*Testing Standards|^# .*Deliverable Types' "${agents_file}"; then
  echo "Found validation policy duplicated outside section 2.6." >&2
  exit 1
fi

echo "Checking extraction-ready record schemas..."
grep -Fq '### OBS-001' "${retro_reference}"
grep -Fq '### PART-001' "${retro_reference}"
grep -Fq '### LEARN-001' "${learnings_reference}"
grep -Fq -- '- Confidence: low | medium | high' "${learnings_reference}"
grep -Fq -- '- Tags: [tag-one, tag-two]' "${learnings_reference}"

echo "Checking produced learning artifacts..."
grep -Eq '^### OBS-[0-9]{3} ' "${retro_file}"
grep -Eq '^### PART-[0-9]{3} ' "${retro_file}"
grep -Eq '^### FOLLOW-[0-9]{3} ' "${retro_file}"
grep -Eq '^### LEARN-[0-9]{3} ' "${learnings_file}"
grep -Eq '^- Confidence: (low|medium|high)$' "${learnings_file}"
grep -Eq '^- Tags: \[[a-z0-9-]+(, [a-z0-9-]+)*\]$' "${learnings_file}"

echo "Checking active backlog contract..."
grep -Fq 'status_values: [todo, in-progress, blocked, done, deferred, cancelled]' "${backlog_file}"
grep -Fq 'approval_values: [not-required, pending, approved]' "${backlog_file}"
grep -Fq 'blocked_reason:' "${backlog_file}"
grep -Fq 'dependencies:' "${backlog_file}"
grep -Fq 'evidence:' "${backlog_file}"
grep -Fq 'history:' "${backlog_file}"
grep -Fq 'turn_id:' "${backlog_file}"

echo "Validation complete."
