/**
 * Sprint Index Manager
 *
 * Manages the centralized sprint index (planning/sprint-index.yaml).
 * The index is a derived, regenerable cache of sprint metadata sourced from
 * individual sprint manifests.
 *
 * Key principles:
 * - Single source of truth: Sprint manifests remain authoritative
 * - Derived data: Index computed from manifests, never manually edited
 * - Regenerable: Can be rebuilt from scratch at any time
 * - Atomic updates: Uses temp file + rename for safe writes
 */

import { join } from 'path';
import { promises as fs } from 'fs';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { logger } from './logger.js';
import {
  fileExists,
  readFile,
  writeFile,
  listDirectories,
} from './file-utils.js';
import type {
  SprintIndex,
  SprintIndexEntry,
  SprintStatistics,
} from '../types/sprint-index.js';
import type { SprintManifest } from '../types/sprint.js';

/**
 * Path to the sprint index file
 */
const SPRINT_INDEX_PATH = join(process.cwd(), 'planning', 'sprint-index.yaml');

/**
 * Path to the planning directory containing sprint manifests
 */
const PLANNING_DIR = join(process.cwd(), 'planning');

/**
 * Header comment for the generated index file
 */
const INDEX_FILE_HEADER = `# Sprint Index
#
# DO NOT EDIT THIS FILE MANUALLY
#
# This is a derived, regenerable cache of sprint metadata sourced from
# individual sprint manifests. It is automatically updated by MCP tools.
#
# To regenerate from scratch: Use the regenerate-sprint-index tool
#
# Generated: ${new Date().toISOString()}
#

`;

/**
 * Load the sprint index from disk
 *
 * If the index file doesn't exist, returns an empty index structure.
 * If the file exists but is invalid YAML, throws an error.
 *
 * @returns Promise<SprintIndex> The loaded or empty index
 * @throws Error if index file exists but cannot be parsed
 */
export async function loadSprintIndex(): Promise<SprintIndex> {
  logger.debug('Loading sprint index from disk');

  if (!(await fileExists(SPRINT_INDEX_PATH))) {
    logger.info('Sprint index does not exist, returning empty index');
    return createEmptyIndex();
  }

  try {
    const content = await readFile(SPRINT_INDEX_PATH);
    const index = parseYaml(content) as SprintIndex;

    logger.info(
      `Loaded sprint index: ${index.totalSprints} sprints (${index.activeSprints} active, ${index.completedSprints} completed)`
    );

    return index;
  } catch (error) {
    logger.error('Failed to parse sprint index', error);
    throw new Error(
      `Failed to parse sprint index at ${SPRINT_INDEX_PATH}: ${error}`
    );
  }
}

/**
 * Save the sprint index to disk with atomic write
 *
 * Uses a temporary file and atomic rename to prevent corruption.
 * Creates a backup of the previous index if it exists.
 *
 * @param index The sprint index to save
 * @throws Error if write operation fails
 */
export async function saveSprintIndex(index: SprintIndex): Promise<void> {
  logger.debug('Saving sprint index to disk');

  // Update generation timestamp
  index.generatedAt = new Date().toISOString();

  // Create backup if index exists
  if (await fileExists(SPRINT_INDEX_PATH)) {
    const backupPath = `${SPRINT_INDEX_PATH}.backup`;
    try {
      await fs.copyFile(SPRINT_INDEX_PATH, backupPath);
      logger.debug(`Created backup at ${backupPath}`);
    } catch (error) {
      logger.warn('Failed to create backup of sprint index', error);
      // Non-fatal: continue with save
    }
  }

  // Write to temporary file
  const tempPath = `${SPRINT_INDEX_PATH}.tmp`;
  const yamlContent = stringifyYaml(index, {
    lineWidth: 0, // Disable line wrapping
    indent: 2,
  });
  const fullContent = INDEX_FILE_HEADER + yamlContent;

  try {
    await writeFile(tempPath, fullContent);

    // Atomic rename
    await fs.rename(tempPath, SPRINT_INDEX_PATH);

    logger.info(
      `Saved sprint index: ${index.totalSprints} sprints (${index.activeSprints} active, ${index.completedSprints} completed)`
    );
  } catch (error) {
    // Clean up temp file if it exists
    try {
      await fs.unlink(tempPath);
    } catch {
      // Ignore cleanup errors
    }

    logger.error('Failed to save sprint index', error);
    throw new Error(`Failed to save sprint index: ${error}`);
  }
}

/**
 * Add a new sprint to the index
 *
 * Loads the current index, adds the new sprint entry, recomputes statistics,
 * and saves the updated index.
 *
 * @param entry The sprint entry to add
 * @throws Error if sprint already exists in index
 */
export async function addSprintToIndex(
  entry: SprintIndexEntry
): Promise<void> {
  logger.info(`Adding sprint to index: ${entry.id}`);

  const index = await loadSprintIndex();

  // Check if sprint already exists
  const existingIndex = index.sprints.findIndex((s) => s.id === entry.id);
  if (existingIndex !== -1) {
    logger.warn(`Sprint ${entry.id} already exists in index, skipping add`);
    throw new Error(`Sprint ${entry.id} already exists in index`);
  }

  // Add new entry
  index.sprints.push(entry);

  // Sort sprints by number (extracted from id: sprint-N-hash)
  index.sprints.sort((a, b) => {
    const numA = parseInt(a.id.match(/sprint-(\d+)-/)?.[1] || '0');
    const numB = parseInt(b.id.match(/sprint-(\d+)-/)?.[1] || '0');
    return numA - numB;
  });

  // Recompute statistics
  index.statistics = computeStatistics(index.sprints);
  index.totalSprints = index.sprints.length;
  index.activeSprints = index.sprints.filter(
    (s) => s.status !== 'complete'
  ).length;
  index.completedSprints = index.sprints.filter(
    (s) => s.status === 'complete'
  ).length;

  await saveSprintIndex(index);
  logger.info(`Successfully added sprint ${entry.id} to index`);
}

/**
 * Update an existing sprint in the index
 *
 * Loads the current index, updates the matching sprint entry, recomputes
 * statistics, and saves the updated index.
 *
 * @param sprintId The sprint ID to update
 * @param updates Partial sprint entry with fields to update
 * @throws Error if sprint not found in index
 */
export async function updateSprintInIndex(
  sprintId: string,
  updates: Partial<SprintIndexEntry>
): Promise<void> {
  logger.info(`Updating sprint in index: ${sprintId}`);

  const index = await loadSprintIndex();

  const sprintIndex = index.sprints.findIndex((s) => s.id === sprintId);
  if (sprintIndex === -1) {
    logger.error(`Sprint ${sprintId} not found in index`);
    throw new Error(`Sprint ${sprintId} not found in index`);
  }

  // Merge updates into existing entry
  index.sprints[sprintIndex] = {
    ...index.sprints[sprintIndex],
    ...updates,
  };

  // Recompute statistics
  index.statistics = computeStatistics(index.sprints);
  index.totalSprints = index.sprints.length;
  index.activeSprints = index.sprints.filter(
    (s) => s.status !== 'complete'
  ).length;
  index.completedSprints = index.sprints.filter(
    (s) => s.status === 'complete'
  ).length;

  await saveSprintIndex(index);
  logger.info(`Successfully updated sprint ${sprintId} in index`);
}

/**
 * Regenerate the entire sprint index from manifests
 *
 * Scans the planning directory for all sprint manifests, extracts metadata,
 * and rebuilds the index from scratch. This is the recovery mechanism if
 * the index becomes corrupted or out of sync.
 *
 * @returns Promise<SprintIndex> The regenerated index
 */
export async function regenerateSprintIndex(): Promise<SprintIndex> {
  logger.info('Regenerating sprint index from manifests');

  const sprintDirs = await listDirectories(PLANNING_DIR);
  const entries: SprintIndexEntry[] = [];

  for (const sprintDir of sprintDirs) {
    // Skip non-sprint directories (e.g., planning/sprint-index.yaml)
    const dirName = sprintDir.split('/').pop() || '';
    if (!dirName.startsWith('sprint-')) {
      continue;
    }

    const manifestPath = join(sprintDir, 'sprint-manifest.yaml');

    if (await fileExists(manifestPath)) {
      try {
        const manifestContent = await readFile(manifestPath);
        const manifest = parseYaml(manifestContent) as SprintManifest;

        // Extract worktree path if it exists
        const worktreePath = join('.worktrees', dirName);
        const worktreeExists = await fileExists(worktreePath);

        // Create index entry from manifest
        const entry: SprintIndexEntry = {
          id: manifest.id,
          title: manifest.title,
          status: manifest.status,
          owner: manifest.owner,
          createdAt: manifest.createdAt,
          manifestPath: join('planning', dirName, 'sprint-manifest.yaml'),
          branch: manifest.links?.branch || `feature/${manifest.id}`,
        };

        // Add optional fields if present
        if ((manifest as any).startedAt) {
          entry.startedAt = (manifest as any).startedAt;
        }
        if ((manifest as any).completedAt) {
          entry.completedAt = (manifest as any).completedAt;
        }
        if ((manifest as any).completionMode) {
          entry.completionMode = (manifest as any).completionMode;
        }
        if (manifest.links?.pr) {
          entry.pr = manifest.links.pr;
        }
        if (worktreeExists) {
          entry.worktreePath = worktreePath;
        }

        entries.push(entry);
        logger.debug(`Added sprint ${manifest.id} to regenerated index`);
      } catch (error) {
        logger.warn(`Failed to parse manifest at ${manifestPath}`, error);
        // Continue processing other manifests
      }
    }
  }

  // Sort sprints by number
  entries.sort((a, b) => {
    const numA = parseInt(a.id.match(/sprint-(\d+)-/)?.[1] || '0');
    const numB = parseInt(b.id.match(/sprint-(\d+)-/)?.[1] || '0');
    return numA - numB;
  });

  // Build index
  const index: SprintIndex = {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    totalSprints: entries.length,
    activeSprints: entries.filter((s) => s.status !== 'complete').length,
    completedSprints: entries.filter((s) => s.status === 'complete').length,
    sprints: entries,
    statistics: computeStatistics(entries),
  };

  await saveSprintIndex(index);

  logger.info(
    `Successfully regenerated index with ${index.totalSprints} sprints`
  );

  return index;
}

/**
 * Create an empty sprint index
 *
 * @returns SprintIndex An empty index with default values
 */
function createEmptyIndex(): SprintIndex {
  return {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    totalSprints: 0,
    activeSprints: 0,
    completedSprints: 0,
    sprints: [],
    statistics: {
      byStatus: {
        planning: 0,
        'in-progress': 0,
        validating: 0,
        verifying: 0,
        published: 0,
        complete: 0,
      },
      byCompletionMode: {
        normal: 0,
        forced: 0,
      },
    },
  };
}

/**
 * Compute statistics from sprint entries
 *
 * @param entries Array of sprint index entries
 * @returns SprintStatistics Computed statistics
 */
function computeStatistics(entries: SprintIndexEntry[]): SprintStatistics {
  const stats: SprintStatistics = {
    byStatus: {
      planning: 0,
      'in-progress': 0,
      validating: 0,
      verifying: 0,
      published: 0,
      complete: 0,
    },
    byCompletionMode: {
      normal: 0,
      forced: 0,
    },
  };

  // Count by status
  for (const entry of entries) {
    stats.byStatus[entry.status] = (stats.byStatus[entry.status] || 0) + 1;
  }

  // Count by completion mode
  for (const entry of entries) {
    if (entry.completionMode) {
      stats.byCompletionMode[entry.completionMode]++;
    }
  }

  // Compute average sprint duration (for completed sprints with both dates)
  const completedWithDuration = entries.filter(
    (e) => e.createdAt && e.completedAt
  );

  if (completedWithDuration.length > 0) {
    const totalDurationMs = completedWithDuration.reduce((sum, entry) => {
      const start = new Date(entry.createdAt).getTime();
      const end = new Date(entry.completedAt!).getTime();
      return sum + (end - start);
    }, 0);

    const avgDurationMs = totalDurationMs / completedWithDuration.length;
    const avgDurationHours = Math.round(avgDurationMs / (1000 * 60 * 60));

    // Format as ISO 8601 duration (e.g., "PT8H" for 8 hours)
    stats.averageSprintDuration = `PT${avgDurationHours}H`;
  }

  return stats;
}
