/**
 * Sprint Index Manager
 *
 * Manages the centralized sprint index (planning/sprint-index.yaml).
 * The index is a derived, regenerable cache of sprint metadata sourced from
 * individual sprint manifests.
 *
 * Key principles:
 * - Single source of truth: Sprint manifests remain authoritative
 * - Derived data: Index computed from manifests, never manually edited
 * - Regenerable: Can be rebuilt from scratch at any time
 * - Atomic updates: Uses temp file + rename for safe writes
 */

import { join } from 'path';
import { promises as fs } from 'fs';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { logger } from './logger.js';
import {
  fileExists,
  readFile,
  writeFile,
  listDirectories,
  listFiles,
} from './file-utils.js';
import {
  getPlanningDir,
  getSprintIndexPath,
} from './project-config.js';
import type {
  SprintIndex,
  SprintIndexEntry,
  SprintStatistics,
} from '../types/sprint-index.js';
import type { SprintManifest } from '../types/sprint.js';
import type { ArchiveConfig } from '../types/archive-config.js';

/**
 * Header comment for the generated index file
 */
const INDEX_FILE_HEADER = `# Sprint Index
#
# DO NOT EDIT THIS FILE MANUALLY
#
# This is a derived, regenerable cache of sprint metadata sourced from
# individual sprint manifests. It is automatically updated by MCP tools.
#
# To regenerate from scratch: Use the regenerate-sprint-index tool
#
# Generated: ${new Date().toISOString()}
#

`;

/**
 * Load the sprint index from disk
 *
 * If the index file doesn't exist, returns an empty index structure.
 * If the file exists but is invalid YAML, throws an error.
 *
 * @returns Promise<SprintIndex> The loaded or empty index
 * @throws Error if index file exists but cannot be parsed
 */
export async function loadSprintIndex(): Promise<SprintIndex> {
  logger.debug('Loading sprint index from disk');

  const indexPath = getSprintIndexPath();

  if (!(await fileExists(indexPath))) {
    logger.info('Sprint index does not exist, returning empty index');
    return createEmptyIndex();
  }

  try {
    const content = await readFile(indexPath);
    const index = parseYaml(content) as SprintIndex;

    logger.info(
      `Loaded sprint index: ${index.totalSprints} sprints (${index.activeSprints} active, ${index.completedSprints} completed)`
    );

    return index;
  } catch (error) {
    logger.error('Failed to parse sprint index', error);
    throw new Error(
      `Failed to parse sprint index at ${indexPath}: ${error}`
    );
  }
}

/**
 * Save the sprint index to disk with atomic write
 *
 * Uses a temporary file and atomic rename to prevent corruption.
 * Creates a backup of the previous index if it exists.
 *
 * @param index The sprint index to save
 * @throws Error if write operation fails
 */
export async function saveSprintIndex(index: SprintIndex): Promise<void> {
  logger.debug('Saving sprint index to disk');

  const indexPath = getSprintIndexPath();

  // Update generation timestamp
  index.generatedAt = new Date().toISOString();

  // Create backup if index exists
  if (await fileExists(indexPath)) {
    const backupPath = `${indexPath}.backup`;
    try {
      await fs.copyFile(indexPath, backupPath);
      logger.debug(`Created backup at ${backupPath}`);
    } catch (error) {
      logger.warn('Failed to create backup of sprint index', error);
      // Non-fatal: continue with save
    }
  }

  // Write to temporary file
  const tempPath = `${indexPath}.tmp`;
  const yamlContent = stringifyYaml(index, {
    lineWidth: 0, // Disable line wrapping
    indent: 2,
  });
  const fullContent = INDEX_FILE_HEADER + yamlContent;

  try {
    await writeFile(tempPath, fullContent);

    // Atomic rename
    await fs.rename(tempPath, indexPath);

    logger.info(
      `Saved sprint index: ${index.totalSprints} sprints (${index.activeSprints} active, ${index.completedSprints} completed)`
    );
  } catch (error) {
    // Clean up temp file if it exists
    try {
      await fs.unlink(tempPath);
    } catch {
      // Ignore cleanup errors
    }

    logger.error('Failed to save sprint index', error);
    throw new Error(`Failed to save sprint index: ${error}`);
  }
}

/**
 * Add a new sprint to the index
 *
 * Loads the current index, adds the new sprint entry, recomputes statistics,
 * and saves the updated index.
 *
 * @param entry The sprint entry to add
 * @throws Error if sprint already exists in index
 */
export async function addSprintToIndex(
  entry: SprintIndexEntry
): Promise<void> {
  logger.info(`Adding sprint to index: ${entry.id}`);

  const index = await loadSprintIndex();

  // Check if sprint already exists
  const existingIndex = index.sprints.findIndex((s) => s.id === entry.id);
  if (existingIndex !== -1) {
    logger.warn(`Sprint ${entry.id} already exists in index, skipping add`);
    throw new Error(`Sprint ${entry.id} already exists in index`);
  }

  // Add new entry
  index.sprints.push(entry);

  // Sort sprints by number (extracted from id: sprint-N-hash)
  index.sprints.sort((a, b) => {
    const numA = parseInt(a.id?.match(/sprint-(\d+)-/)?.[1] || '0');
    const numB = parseInt(b.id?.match(/sprint-(\d+)-/)?.[1] || '0');
    return numA - numB;
  });

  // Recompute statistics
  index.statistics = computeStatistics(index.sprints);
  index.totalSprints = index.sprints.length;
  index.activeSprints = index.sprints.filter(
    (s) => s.status !== 'complete'
  ).length;
  index.completedSprints = index.sprints.filter(
    (s) => s.status === 'complete'
  ).length;

  await saveSprintIndex(index);
  logger.info(`Successfully added sprint ${entry.id} to index`);
}

/**
 * Update an existing sprint in the index
 *
 * Loads the current index, updates the matching sprint entry, recomputes
 * statistics, and saves the updated index.
 *
 * @param sprintId The sprint ID to update
 * @param updates Partial sprint entry with fields to update
 * @throws Error if sprint not found in index
 */
export async function updateSprintInIndex(
  sprintId: string,
  updates: Partial<SprintIndexEntry>
): Promise<void> {
  logger.info(`Updating sprint in index: ${sprintId}`);

  const index = await loadSprintIndex();

  const sprintIndex = index.sprints.findIndex((s) => s.id === sprintId);
  if (sprintIndex === -1) {
    logger.error(`Sprint ${sprintId} not found in index`);
    throw new Error(`Sprint ${sprintId} not found in index`);
  }

  // Filter out undefined values from updates to avoid overwriting existing fields
  const cleanUpdates = Object.fromEntries(
    Object.entries(updates).filter(([_, value]) => value !== undefined)
  );

  // Merge updates into existing entry
  index.sprints[sprintIndex] = {
    ...index.sprints[sprintIndex],
    ...cleanUpdates,
  };

  // Recompute statistics
  index.statistics = computeStatistics(index.sprints);
  index.totalSprints = index.sprints.length;
  index.activeSprints = index.sprints.filter(
    (s) => s.status !== 'complete'
  ).length;
  index.completedSprints = index.sprints.filter(
    (s) => s.status === 'complete'
  ).length;

  await saveSprintIndex(index);
  logger.info(`Successfully updated sprint ${sprintId} in index`);
}

/**
 * Update manifest path for a sprint in the index
 *
 * Helper function for archive-sprint tool to update the manifestPath
 * when moving sprints from active/ to archive/{year}/.
 *
 * @param sprintId - Sprint identifier
 * @param manifestPath - New manifest path relative to project root
 * @throws Error if sprint not found in index
 *
 * @example
 * ```typescript
 * await updateSprintIndexPath(
 *   'sprint-12-sdwpw0',
 *   'planning/archive/2026/sprint-12-sdwpw0/sprint-manifest.yaml'
 * );
 * ```
 */
export async function updateSprintIndexPath(
  sprintId: string,
  manifestPath: string
): Promise<void> {
  logger.info(`Updating manifest path for ${sprintId} to ${manifestPath}`);
  await updateSprintInIndex(sprintId, { manifestPath });
}

/**
 * Result of sprint index regeneration including diagnostics
 */
export interface RegenerateResult {
  index: SprintIndex;
  skippedDirectories: number;
  repairedDirectories: number;
}

/**
 * Options for sprint index regeneration
 */
export interface RegenerateOptions {
  /** Create minimal manifests for directories missing them */
  repair?: boolean;
}

/**
 * Create a minimal sprint manifest for a directory without one
 *
 * @param dirName Sprint directory name (e.g., "sprint-123-abc456")
 * @param sprintDir Full path to sprint directory
 * @returns Promise<SprintManifest | null> The created manifest or null if unable
 */
async function createMinimalManifest(
  dirName: string,
  sprintDir: string
): Promise<SprintManifest | null> {
  logger.info(`Creating minimal manifest for ${dirName}`);

  // Extract sprint number from directory name (sprint-123-abc or sprint-123)
  const match = dirName.match(/^sprint-(\d+)(?:-(.+))?$/);
  if (!match) {
    logger.warn(`Cannot parse sprint ID from directory name: ${dirName}`);
    return null;
  }

  const sprintNumber = match[1];
  const sprintHash = match[2] || 'unknown';
  const sprintId = `sprint-${sprintNumber}-${sprintHash}`;

  // Check if directory has any files (don't create manifests for empty dirs)
  const files = await listFiles(sprintDir);
  if (files.length === 0) {
    logger.warn(`Directory ${dirName} is empty, skipping manifest creation`);
    return null;
  }

  // Try to get directory creation/modification time
  let createdAt: string;
  try {
    const stats = await fs.stat(sprintDir);
    createdAt = stats.birthtime.toISOString();
  } catch {
    createdAt = new Date().toISOString();
  }

  const manifest: SprintManifest = {
    id: sprintId,
    title: `Sprint ${sprintNumber} (Auto-generated)`,
    goal: 'No goal specified - manifest was auto-generated during repair',
    owner: 'Unknown',
    createdAt,
    status: 'complete', // Existing directories are likely completed sprints
    links: {
      branch: `feature/${sprintId}`,
    },
  };

  return manifest;
}

/**
 * Check if archive system is enabled
 *
 * Reads archive-config.yaml to determine if archive structure is in use.
 * Falls back to flat structure if config doesn't exist or archive is disabled.
 */
async function isArchiveEnabled(): Promise<boolean> {
  const planningDir = getPlanningDir();
  const configPath = join(planningDir, 'archive-config.yaml');

  if (!(await fileExists(configPath))) {
    return false;
  }

  try {
    const configContent = await readFile(configPath);
    const config = parseYaml(configContent) as { archive: ArchiveConfig };
    return config.archive?.enabled === true;
  } catch (err) {
    logger.warn('Failed to read archive-config.yaml, assuming flat structure', err);
    return false;
  }
}

/**
 * Get list of sprint directories to scan
 *
 * If archive system is enabled, scans:
 * - planning/active/
 * - planning/archive/{year}/
 * - planning/ root (for legacy sprints not yet migrated)
 *
 * Otherwise, scans flat structure:
 * - planning/
 */
async function getSprintDirectories(): Promise<string[]> {
  const planningDir = getPlanningDir();
  const archiveEnabled = await isArchiveEnabled();

  if (!archiveEnabled) {
    // Flat structure: scan planning/ directly
    logger.debug('Using flat structure, scanning planning/ directory');
    return await listDirectories(planningDir);
  }

  // Archive structure: scan active/, archive/{year}/, and planning root for legacy sprints
  logger.debug('Using archive structure, scanning active/, archive/, and planning root directories');
  const sprintDirs: string[] = [];

  // Scan active/
  const activeDir = join(planningDir, 'active');
  if (await fileExists(activeDir)) {
    const activeDirs = await listDirectories(activeDir);
    sprintDirs.push(...activeDirs);
    logger.debug(`Found ${activeDirs.length} sprints in active/`);
  }

  // Scan archive/{year}/
  const archiveDir = join(planningDir, 'archive');
  const archiveCount = sprintDirs.length;
  if (await fileExists(archiveDir)) {
    const yearDirs = await listDirectories(archiveDir);
    for (const yearDir of yearDirs) {
      const archivedDirs = await listDirectories(yearDir);
      sprintDirs.push(...archivedDirs);
    }
    logger.debug(`Found ${sprintDirs.length - archiveCount} sprints in archive/`);
  }

  // Scan planning root for legacy sprint directories (not yet migrated)
  // Filter out known non-sprint directories
  const rootDirs = await listDirectories(planningDir);
  const legacyDirs = rootDirs.filter((dir) => {
    const dirName = dir.split('/').pop() || '';
    // Only include directories that start with 'sprint-'
    // Exclude active/, archive/, knowledge/, and other system directories
    return (
      dirName.startsWith('sprint-') &&
      !dir.includes('/active/') &&
      !dir.includes('/archive/') &&
      !dir.includes('/knowledge/')
    );
  });

  if (legacyDirs.length > 0) {
    sprintDirs.push(...legacyDirs);
    logger.debug(`Found ${legacyDirs.length} legacy sprints in planning root (not yet migrated)`);
  }

  return sprintDirs;
}

/**
 * Regenerate the entire sprint index from manifests
 *
 * Scans the planning directory for all sprint manifests, extracts metadata,
 * and rebuilds the index from scratch. This is the recovery mechanism if
 * the index becomes corrupted or out of sync.
 *
 * Supports both flat structure and active/archive hierarchy:
 * - Flat: Scans planning/ directly (legacy)
 * - Archive: Scans planning/active/ and planning/archive/{year}/
 *
 * Structure is determined by archive-config.yaml existence and enabled flag.
 *
 * @param options Regeneration options
 * @returns Promise<RegenerateResult> The regenerated index and diagnostics
 */
export async function regenerateSprintIndex(
  options: RegenerateOptions = {}
): Promise<RegenerateResult> {
  logger.info('Regenerating sprint index from manifests');

  const sprintDirs = await getSprintDirectories();
  const entries: SprintIndexEntry[] = [];
  let skippedCount = 0;
  let repairedCount = 0;

  for (const sprintDir of sprintDirs) {
    // Skip non-sprint directories (e.g., active/, archive/, sprint-index.yaml)
    const dirName = sprintDir.split('/').pop() || '';
    if (!dirName.startsWith('sprint-')) {
      continue;
    }

    const manifestPath = join(sprintDir, 'sprint-manifest.yaml');

    if (!(await fileExists(manifestPath))) {
      // Repair mode: try to create minimal manifest
      if (options.repair) {
        logger.info(`Attempting to repair ${dirName} by creating minimal manifest`);
        const minimalManifest = await createMinimalManifest(dirName, sprintDir);

        if (minimalManifest) {
          try {
            const manifestContent = stringifyYaml(minimalManifest, {
              lineWidth: 0,
              indent: 2,
            });
            await writeFile(manifestPath, manifestContent);
            logger.info(`Created minimal manifest for ${dirName}`);
            repairedCount++;
            // Continue to process this manifest below
          } catch (error) {
            logger.error(`Failed to write manifest for ${dirName}`, error);
            skippedCount++;
            continue;
          }
        } else {
          logger.warn(`Could not create minimal manifest for ${dirName}, skipping`);
          skippedCount++;
          continue;
        }
      } else {
        logger.warn(`Sprint directory ${dirName} has no sprint-manifest.yaml, skipping`);
        skippedCount++;
        continue;
      }
    }

    try {
        const manifestContent = await readFile(manifestPath);
        const manifest = parseYaml(manifestContent) as SprintManifest;

        // Skip manifests without required id field
        if (!manifest.id) {
          logger.warn(`Manifest at ${manifestPath} missing required 'id' field, skipping`);
          continue;
        }

        // Extract worktree path if it exists
        const worktreePath = join('.worktrees', dirName);
        const worktreeExists = await fileExists(worktreePath);

        // Calculate relative manifest path from planning directory
        // sprintDir is absolute path, need to make it relative to planning/
        const planningDir = getPlanningDir();
        const relativePath = sprintDir.replace(planningDir + '/', '');
        const relativeManifestPath = join('planning', relativePath, 'sprint-manifest.yaml');

        // Create index entry from manifest
        const entry: SprintIndexEntry = {
          id: manifest.id,
          title: manifest.title,
          status: manifest.status,
          owner: manifest.owner,
          createdAt: manifest.createdAt,
          manifestPath: relativeManifestPath,
          branch: manifest.links?.branch || `feature/${manifest.id}`,
        };

        // Add optional fields if present
        if ((manifest as any).startedAt) {
          entry.startedAt = (manifest as any).startedAt;
        }
        if ((manifest as any).completedAt) {
          entry.completedAt = (manifest as any).completedAt;
        }
        if ((manifest as any).completionMode) {
          entry.completionMode = (manifest as any).completionMode;
        }
        if (manifest.links?.pr) {
          entry.pr = manifest.links.pr;
        }
        if (worktreeExists) {
          entry.worktreePath = worktreePath;
        }

        entries.push(entry);
        logger.debug(`Added sprint ${manifest.id} to regenerated index`);
      } catch (error) {
        logger.warn(`Failed to parse manifest at ${manifestPath}`, error);
        // Continue processing other manifests
      }
  }

  // Sort sprints by number
  entries.sort((a, b) => {
    const numA = parseInt(a.id?.match(/sprint-(\d+)-/)?.[1] || '0');
    const numB = parseInt(b.id?.match(/sprint-(\d+)-/)?.[1] || '0');
    return numA - numB;
  });

  // Build index
  const index: SprintIndex = {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    totalSprints: entries.length,
    activeSprints: entries.filter((s) => s.status !== 'complete').length,
    completedSprints: entries.filter((s) => s.status === 'complete').length,
    sprints: entries,
    statistics: computeStatistics(entries),
  };

  await saveSprintIndex(index);

  let logMessage = `Successfully regenerated index with ${index.totalSprints} sprints`;
  if (repairedCount > 0) {
    logMessage += ` (${repairedCount} manifests created)`;
  }
  if (skippedCount > 0) {
    logMessage += ` (${skippedCount} directories skipped)`;
  }

  if (repairedCount > 0 || skippedCount > 0) {
    logger.warn(logMessage);
  } else {
    logger.info(logMessage);
  }

  return { index, skippedDirectories: skippedCount, repairedDirectories: repairedCount };
}

/**
 * Create an empty sprint index
 *
 * @returns SprintIndex An empty index with default values
 */
function createEmptyIndex(): SprintIndex {
  return {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    totalSprints: 0,
    activeSprints: 0,
    completedSprints: 0,
    sprints: [],
    statistics: {
      byStatus: {
        planning: 0,
        'in-progress': 0,
        validating: 0,
        verifying: 0,
        published: 0,
        complete: 0,
      },
      byCompletionMode: {
        normal: 0,
        forced: 0,
      },
    },
  };
}

/**
 * Compute statistics from sprint entries
 *
 * @param entries Array of sprint index entries
 * @returns SprintStatistics Computed statistics
 */
function computeStatistics(entries: SprintIndexEntry[]): SprintStatistics {
  const stats: SprintStatistics = {
    byStatus: {
      planning: 0,
      'in-progress': 0,
      validating: 0,
      verifying: 0,
      published: 0,
      complete: 0,
    },
    byCompletionMode: {
      normal: 0,
      forced: 0,
    },
  };

  // Count by status
  for (const entry of entries) {
    stats.byStatus[entry.status] = (stats.byStatus[entry.status] || 0) + 1;
  }

  // Count by completion mode
  for (const entry of entries) {
    if (entry.completionMode) {
      stats.byCompletionMode[entry.completionMode]++;
    }
  }

  // Compute average sprint duration (for completed sprints with both dates)
  const completedWithDuration = entries.filter(
    (e) => e.createdAt && e.completedAt
  );

  if (completedWithDuration.length > 0) {
    const totalDurationMs = completedWithDuration.reduce((sum, entry) => {
      const start = new Date(entry.createdAt).getTime();
      const end = new Date(entry.completedAt!).getTime();
      return sum + (end - start);
    }, 0);

    const avgDurationMs = totalDurationMs / completedWithDuration.length;
    const avgDurationHours = Math.round(avgDurationMs / (1000 * 60 * 60));

    // Format as ISO 8601 duration (e.g., "PT8H" for 8 hours)
    stats.averageSprintDuration = `PT${avgDurationHours}H`;
  }

  return stats;
}
